#!/bin/bash
 
# Name of job:
#PBS -N test1
 
# Where to write stderr:
#PBS -e log/test1.err
 
# Where to write stdout: 
#PBS -o log/test1.out
 
# Specify number of nodes, processors (really threads) per node, and the maximum allowed run time for the job
# Can also specify max memory requested with something like mem=10gb
#PBS-l nodes=1:ppn=80,walltime=144:00:00

# Keep job output and joint output and error
#PBS -k o
#PBS -j oe

# Change directory to the directory the job was submitted from
cd $PBS_O_WORKDIR

# Run the program
python3 /home/users/michael_butts/.local/lib/python3.10/site-packages/lab_space/bin/labspace -e rl_expt1 -r -s -tt 1 -tp 80

